### ISSUE TITLE
Base station camera protocol implementation

### ISSUE THREAD

**Issue by layneson** [2535Rover/RoverSystem#61]
A basic implementation of the camera protocol, which for now will display a single camera feed in an SDL window. The camera protocol spec will be merged into master shortly (it will be in the docs directory). For the purpose of this task, a test program will be supplied which will feed camera frames to the "base station", so that only the base station side must be implemented. When this task is complete, it will be modified to fit with the other base station tasks, so don't worry about integration. Simply integrate with the network library to display a real-time feed.

**Comment by HenryBurns** [comment]
It's working!
